name: nodeci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install
      run: npm install
    - name: Run Tests
      run: npm test
    
